[package]
name = "advent_of_code_framework"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8"
bitvec = "1.0"
colored = "3.0"
hashbrown = "0.16"
itertools = "0.14"
num = "0.4"
paste = "1.0"
thiserror = "2.0"
ureq = "3.1"